# Python Arithmetic

In programming and math, these are expressions that follow the rules of PEMDAS. Below are the symbols used in Python for mathematical expressions.

## Operators in Python

In [1]:
# Parentheses
(1 + 1) * 3

6

In [2]:
# Exponent: Notice it has two * characters and no spaces in between.
2 ** 4

16

In [3]:
# Multiplication
2 * 4

8

In [4]:
# Division
9 / 8

1.125

In [5]:
# Integer Division: Notice it has two / characters and no spaces in between.
9 // 8

1

In [6]:
# Modulo Division
5 % 2

1

In [7]:
# Addition
2 + 6

8

In [8]:
# Subtraction
4 - 2

2

***QUESTION: What is the difference between Integer Division and Modulo Division?***

## Expression Errors in Python

In [9]:
# Read the Exception Message, what does it mean?
* 4

SyntaxError: can't use starred expression here (842530021.py, line 2)

In [10]:
# Read the Exception Message, what can tell you where to start troubleshooting?
2 * * 4

SyntaxError: invalid syntax (741663770.py, line 2)

### Example Expressions

Using the rules of PEMDAS, predict how each expression will be evaluated.

In [11]:
# Expression 1
2 + 3 * -5

-13

In [12]:
# Expression 2
(2 + 3) * -5

-25

In [13]:
# Expression 3
-(1 + 1) + 2 * (3 * 4 * 5 / 6) ** 3 + 7 + 8 + 9

2022.0

## Text Data Type

You can use either the single or double quote when creating a String value. The key is, if you open with a double quote you must close it with a double quote, and vice versa.

In [14]:
# String Using Single Quote
'Hello'

'Hello'

In [15]:
# String Using Double Quote
"World"

'World'

## Identifer Names

### Rules

1. May only use alphabet or numerical characters
1. May use the underscore _ character
1. First character must be a letter or underscore
1. Should try to ensure name has meaning to the expression or value
1. Identifer name is first, then equal sign to assign an expression or value

### Example

* identifier = "value"
* x = 1
* sample = 1 / 2
* snake_case = "Identifer name uses underscore to separate words. Preferred"
* camelCase = "Identifer name uses capital letters to separate words."

### Assigning a Value

* The expression or call must first be completed
* Result is then assigned to the identifier

Let's assign the variable _a_:

In [16]:
a = 2

In [17]:
a

2

***QUESTION: What will happen when we attempt to use variable _b_?***

In [18]:
b

NameError: name 'b' is not defined

In [19]:
b = 3
a + b

5

***QUESTION: Can we use the result of _a + b_ in future expressions?***

In [20]:
# COMPLETE: Assign the result of a plus b
total = a + b
total

5

***QUESTION: What will happen to variable _total_ if we reassign variable _a_ to a new value?***

In [21]:
a = 10
total

5

In [22]:
# COMPLETE: Reassign result of expression a plus b to total
total = a + b
total

13

In [23]:
# The line below causes a syntax error
a + b = total

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (1630286564.py, line 2)

In [24]:
a = a + 1
a

11

In [25]:
# What does this do?
x = 100
y = 10.25
z = x * y
z

1025.0

### Why Names?

A cell with arithmetic but no names is difficult to interpret.

***QUESTION: Without scrolling down, what does Option 1 represent?***

In [26]:
# Option 1
40 * 15.00

600.0

In [27]:
40 * 52 * 15.00

31200.0

***QUESTION: After reading the variable assignments, what does Option 2 represent?***

In [28]:
# Option 2
ca_hourly_minimum_wage = 15.00
hours_per_week = 40
weeks_per_year = 52

In [29]:
hours_per_year = hours_per_week * weeks_per_year

In [30]:
hours_per_year

2080

In [31]:
weekly_wages = hours_per_week * ca_hourly_minimum_wage
weekly_wages

600.0

In [32]:
yearly_wages = hours_per_year * ca_hourly_minimum_wage
yearly_wages

31200.0

***QUESTION: Compare Option 1 and 2, which one demonstrates how on January 1, 2022, the CA Minimum Wage for Employers with 26 Employees or More increased to $15/hour better? Why?***

## Functions and Call Expressions

When a function is used, we say it is "called". Which means you will use the function identifier with a pair of parentheses and any required arguments inside those parenthese to complete the call.

Below are a few example functions that you can call.

### Absolute Value

In [33]:
abs(-5)

5

In [34]:
abs(1 - 3)

2

In [35]:
day_temp = 52
night_temp = 47
abs(night_temp - day_temp)

5

### Minimum and Maximum

In [36]:
min(14, 15)

14

In [37]:
max(24, 42)

42

### Rounding

This uses a combination of positional arguments and named arguments.

In [38]:
round(123.456)

123

In [39]:
round(123.456, 1)

123.5

In [40]:
round(123.456, ndigits=1)

123.5

In [41]:
round?

Signature: round(number, ndigits=None)
Docstring:
Round a number to a given precision in decimal digits.

The return value is an integer if ndigits is omitted or None.  Otherwise
the return value has the same type as the number.  ndigits may be negative.
Type:      builtin_function_or_method

In [42]:
round(number=123.456)

123

In [43]:
# The line below causes a type error because the wrong name was used.
round(123.456, digs=1)

TypeError: 'digs' is an invalid keyword argument for round()

### Imported Functions

There are far more functions available to you than what is in the default install of Python. An import is a way to bring additional functions and classes into your program to do more things.

Just a note for how functions are described. A _method_ is a function that belongs to a class in Python. A _function_ is independent of a class. We will get more into this later, but you may hear the term method or function used.

For example, we can import the _math_ library and check the square root of a number.

In [44]:
# The line below causes an error if math has not been imported
math.sqrt(2)

NameError: name 'math' is not defined

In [45]:
import math

In [46]:
math.sqrt(2)

1.4142135623730951

## Tables

This is one of the most important things we will use in this class. Tables are a way to organize your data for analysis and graphing.

Below are a few of the most common methods used in this class.

In [47]:
# Import all Classes and Functions from the datascience library before you can use it.
from datascience import *

In [48]:
# Read a CSV file and convert it into a table in Python memory
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

### Show Method

Displays the first n rows of a table. If no n is provided, displays all rows.

In [49]:
cones.show(3)

In [50]:
cones.show()

### Select Method

Creates a copy of a table with only the selected columns. Each column is the column name as a string or the integer index of the column.

In [51]:
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
strawberry
chocolate
bubblegum

In [52]:
cones.select('Flavor', 'Price')

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [53]:
# The line below causes an error because Flavor is not a name.
cones.select(Flavor, 'Price')

NameError: name 'Flavor' is not defined

### Drop Method

Creates a copy of a table without the specified columns. Each column is the column name as a string or integer index.

In [54]:
cones.drop('Price')

Flavor     | Color
strawberry | pink
chocolate  | light brown
chocolate  | dark brown
strawberry | pink
chocolate  | dark brown
bubblegum  | pink

In [55]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [56]:
cones_without_price = cones.drop('Price')
cones_without_price

Flavor     | Color
strawberry | pink
chocolate  | light brown
chocolate  | dark brown
strawberry | pink
chocolate  | dark brown
bubblegum  | pink

### Where Method

Filters the table for rows where the predicate is true. Predicate should be one of the provided are.<something> functions. Column can be a string column label or an integer index.

In [57]:
cones.where('Flavor', 'chocolate')

Flavor    | Color       | Price
chocolate | light brown | 4.75
chocolate | dark brown  | 5.25
chocolate | dark brown  | 5.25

### Sort Method

Sorts the rows in the table by the values in the column column_name_or_index in ascending order by default. Set descending=True to sort in descending order.

In [58]:
cones.sort('Price')

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

In [59]:
cones.sort('Price', descending=True)

Flavor     | Color       | Price
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
strawberry | pink        | 3.55

In [60]:
cones.sort('Flavor', descending=True)

Flavor     | Color       | Price
strawberry | pink        | 3.55
strawberry | pink        | 5.25
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

### A more interesting table

In [61]:
# From https://github.com/erikgregorywebb/datasets/blob/master/nba-salaries.csv
nba = Table.read_table('nba_salaries.csv')
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

***QUESTION: How many rows does the table above have?***

In [62]:
point_guards = nba.where('position', 'PG').where('season', 2020)

In [63]:
point_guards

rank | name              | position | team                   | salary   | season
1    | Stephen Curry     | PG       | Golden State Warriors  | 40231758 | 2020
2    | Chris Paul        | PG       | Oklahoma City Thunder  | 38506482 | 2020
3    | Russell Westbrook | PG       | Houston Rockets        | 38506482 | 2020
4    | John Wall         | PG       | Washington Wizards     | 38199000 | 2020
8    | Kyle Lowry        | PG       | Toronto Raptors        | 34996296 | 2020
14   | Kemba Walker      | PG       | Boston Celtics         | 32742000 | 2020
16   | Mike Conley       | PG       | Utah Jazz              | 32511624 | 2020
17   | Kyrie Irving      | PG       | Brooklyn Nets          | 31742000 | 2020
21   | Damian Lillard    | PG       | Portland Trail Blazers | 29802321 | 2020
52   | Malcolm Brogdon   | PG       | Indiana Pacers         | 20000000 | 2020
... (72 rows omitted)

***QUESTION: How many rows does the table above have?***

In [64]:
point_guards.drop('position')

rank | name              | team                   | salary   | season
1    | Stephen Curry     | Golden State Warriors  | 40231758 | 2020
2    | Chris Paul        | Oklahoma City Thunder  | 38506482 | 2020
3    | Russell Westbrook | Houston Rockets        | 38506482 | 2020
4    | John Wall         | Washington Wizards     | 38199000 | 2020
8    | Kyle Lowry        | Toronto Raptors        | 34996296 | 2020
14   | Kemba Walker      | Boston Celtics         | 32742000 | 2020
16   | Mike Conley       | Utah Jazz              | 32511624 | 2020
17   | Kyrie Irving      | Brooklyn Nets          | 31742000 | 2020
21   | Damian Lillard    | Portland Trail Blazers | 29802321 | 2020
52   | Malcolm Brogdon   | Indiana Pacers         | 20000000 | 2020
... (72 rows omitted)

In [65]:
point_guards

rank | name              | position | team                   | salary   | season
1    | Stephen Curry     | PG       | Golden State Warriors  | 40231758 | 2020
2    | Chris Paul        | PG       | Oklahoma City Thunder  | 38506482 | 2020
3    | Russell Westbrook | PG       | Houston Rockets        | 38506482 | 2020
4    | John Wall         | PG       | Washington Wizards     | 38199000 | 2020
8    | Kyle Lowry        | PG       | Toronto Raptors        | 34996296 | 2020
14   | Kemba Walker      | PG       | Boston Celtics         | 32742000 | 2020
16   | Mike Conley       | PG       | Utah Jazz              | 32511624 | 2020
17   | Kyrie Irving      | PG       | Brooklyn Nets          | 31742000 | 2020
21   | Damian Lillard    | PG       | Portland Trail Blazers | 29802321 | 2020
52   | Malcolm Brogdon   | PG       | Indiana Pacers         | 20000000 | 2020
... (72 rows omitted)

***QUESTION: Why is the position column still present when we run the table a second time?***

In [66]:
# COMPLETE: Update the point_guards table to exclude the rank, position, and season columns.
point_guards = point_guards.drop('rank', 'position', 'season')

In [67]:
# COMPLETE: Output the first 10 rows of the table
point_guards.show(10)

In [68]:
# COMPLETE: Sort the point_guards table by salary descending and output the first 10 rows
point_guards.sort('salary', descending=True).show(10)

***QUESTION: Why does the line below cause an error?***

In [69]:
nba.drop('position').where('position', 'PG')

ValueError: label "position" not in labels ('rank', 'name', 'team', 'salary', 'season')