## Python Arithmetic ##

In programming and math, these are expressions that follow the rules of PEMDAS.

In [1]:
# Parentheses
(1 + 1) * 3

6

In [2]:
# Exponent
2 ** 4

16

In [3]:
# Multiplication
2 * 4

8

In [4]:
# Division
9 / 8

1.125

In [5]:
# Integer Division
9 // 8

1

In [6]:
# Modulo (Remainder Division)
5 % 2

1

In [7]:
# Addition
2 + 6

8

In [8]:
# Subtraction
4 - 2

2

In [9]:
# The line below errors
* 4

SyntaxError: can't use starred expression here (1622189663.py, line 2)

In [10]:
# The line below errors 
2 * * 4

SyntaxError: invalid syntax (1438979499.py, line 2)

In [13]:
# Expression 1
2 + 3 * -5

-13

In [14]:
# Expression 2
(2 + 3) * -5

-25

In [15]:
# Expression 3
-(1 + 1) + 2 * (3 * 4 * 5 / 6) ** 3 + 7 + 8 + 9

2022.0

In [16]:
# String
'hello'

'hello'

In [18]:
# String
"Data 8"

'Data 8'

## Identifer Names

### Rules

1. May only use alphabet or numerical characters
1. May use the underscore _ character
1. First character must be a letter or underscore
1. Should try to ensure name has meaning to the expression or value
1. Identifer name is first, then equal sign to assign an expression or value

### Example

* identifier = "value"
* x = 1
* sample = 1 / 2
* snake_case = "Identifer name uses underscore to separate words. Preferred"
* camelCase = "Identifer name uses capital letters to separate words."

In [20]:
a = 2

In [21]:
a

2

In [22]:
# The line below causes a name error if b isn't assigned yet.
b

NameError: name 'b' is not defined

In [23]:
b = 3
a * b

6

In [24]:
a

2

In [25]:
b

3

In [26]:
# Assign result of expression a + b to total
total = a + b
total

5

In [27]:
a = 10
total

5

In [28]:
total

5

In [29]:
a

10

In [30]:
# Reassign result of expression a + b to total
total = a + b
total

13

In [31]:
# The line below causes a syntax error
a + b = total

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (1630286564.py, line 2)

In [32]:
a = a + 1
a

11

In [33]:
# What does this do?
x = 100
y = 10.25
z = x * y
z

1025.0

### Why Names?

A cell with arithmetic but no names is difficult to interpret.

In [34]:
# Option 1
40 * 15.00

600.0

In [35]:
40 * 52 * 15.00

31200.0

On January 1, 2022, the CA Minimum Wage for Employers with 26 Employees or More increased to $15/hour.

In [36]:
# Option 2
ca_hourly_minimum_wage = 15.00
hours_per_week = 40
weeks_per_year = 52

In [37]:
hours_per_year = hours_per_week * weeks_per_year

In [38]:
hours_per_year

2080

In [39]:
weekly_wages = hours_per_week * ca_hourly_minimum_wage
weekly_wages

600.0

In [40]:
yearly_wages = hours_per_year * ca_hourly_minimum_wage
yearly_wages

31200.0

## Functions and Call Expressions

In [41]:
abs(-5)

5

In [42]:
abs(1 - 3)

2

In [43]:
day_temp = 52
night_temp = 47
abs(night_temp - day_temp)

5

In [44]:
min(14, 15)

14

In [45]:
round(123.456)

123

In [46]:
round(123.456, 1)

123.5

In [47]:
round(123.456, ndigits=1)

123.5

In [48]:
round?

Signature: round(number, ndigits=None)
Docstring:
Round a number to a given precision in decimal digits.

The return value is an integer if ndigits is omitted or None.  Otherwise
the return value has the same type as the number.  ndigits may be negative.
Type:      builtin_function_or_method

In [49]:
round(number=123.456)

123

In [50]:
# The line below causes a type error because the wrong name was used.
round(123.456, digs=1)

TypeError: 'digs' is an invalid keyword argument for round()

In [51]:
# The line below causes an error if math has not been imported
math.sqrt(2)

NameError: name 'math' is not defined

In [52]:
import math

In [53]:
math.sqrt(2)

1.4142135623730951

## Tables ##

In [54]:
from datascience import *

In [55]:
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [56]:
cones.show(3)

In [57]:
cones.show()

In [58]:
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
strawberry
chocolate
bubblegum

In [59]:
cones.select('Flavor', 'Price')

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [60]:
# The line below causes an error because Flavor is not a name.
cones.select(Flavor, 'Price')

NameError: name 'Flavor' is not defined

In [61]:
cones.drop('Price')

Flavor     | Color
strawberry | pink
chocolate  | light brown
chocolate  | dark brown
strawberry | pink
chocolate  | dark brown
bubblegum  | pink

In [62]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [63]:
cones_without_price = cones.drop('Price')
cones_without_price

Flavor     | Color
strawberry | pink
chocolate  | light brown
chocolate  | dark brown
strawberry | pink
chocolate  | dark brown
bubblegum  | pink

In [64]:
cones.where('Flavor', 'chocolate')

Flavor    | Color       | Price
chocolate | light brown | 4.75
chocolate | dark brown  | 5.25
chocolate | dark brown  | 5.25

In [65]:
cones.sort('Price')

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

In [66]:
cones.sort('Price', descending=True)

Flavor     | Color       | Price
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
strawberry | pink        | 3.55

In [67]:
cones.sort('Flavor', descending=True)

Flavor     | Color       | Price
strawberry | pink        | 3.55
strawberry | pink        | 5.25
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

### A more interesting table

In [68]:
# From https://github.com/erikgregorywebb/datasets/blob/master/nba-salaries.csv
nba = Table.read_table('nba_salaries.csv')
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [69]:
point_guards = nba.where('position', 'PG').where('season', 2020)

In [70]:
point_guards

rank | name              | position | team                   | salary   | season
1    | Stephen Curry     | PG       | Golden State Warriors  | 40231758 | 2020
2    | Chris Paul        | PG       | Oklahoma City Thunder  | 38506482 | 2020
3    | Russell Westbrook | PG       | Houston Rockets        | 38506482 | 2020
4    | John Wall         | PG       | Washington Wizards     | 38199000 | 2020
8    | Kyle Lowry        | PG       | Toronto Raptors        | 34996296 | 2020
14   | Kemba Walker      | PG       | Boston Celtics         | 32742000 | 2020
16   | Mike Conley       | PG       | Utah Jazz              | 32511624 | 2020
17   | Kyrie Irving      | PG       | Brooklyn Nets          | 31742000 | 2020
21   | Damian Lillard    | PG       | Portland Trail Blazers | 29802321 | 2020
52   | Malcolm Brogdon   | PG       | Indiana Pacers         | 20000000 | 2020
... (72 rows omitted)

In [71]:
point_guards.drop('position')

rank | name              | team                   | salary   | season
1    | Stephen Curry     | Golden State Warriors  | 40231758 | 2020
2    | Chris Paul        | Oklahoma City Thunder  | 38506482 | 2020
3    | Russell Westbrook | Houston Rockets        | 38506482 | 2020
4    | John Wall         | Washington Wizards     | 38199000 | 2020
8    | Kyle Lowry        | Toronto Raptors        | 34996296 | 2020
14   | Kemba Walker      | Boston Celtics         | 32742000 | 2020
16   | Mike Conley       | Utah Jazz              | 32511624 | 2020
17   | Kyrie Irving      | Brooklyn Nets          | 31742000 | 2020
21   | Damian Lillard    | Portland Trail Blazers | 29802321 | 2020
52   | Malcolm Brogdon   | Indiana Pacers         | 20000000 | 2020
... (72 rows omitted)

In [72]:
point_guards

rank | name              | position | team                   | salary   | season
1    | Stephen Curry     | PG       | Golden State Warriors  | 40231758 | 2020
2    | Chris Paul        | PG       | Oklahoma City Thunder  | 38506482 | 2020
3    | Russell Westbrook | PG       | Houston Rockets        | 38506482 | 2020
4    | John Wall         | PG       | Washington Wizards     | 38199000 | 2020
8    | Kyle Lowry        | PG       | Toronto Raptors        | 34996296 | 2020
14   | Kemba Walker      | PG       | Boston Celtics         | 32742000 | 2020
16   | Mike Conley       | PG       | Utah Jazz              | 32511624 | 2020
17   | Kyrie Irving      | PG       | Brooklyn Nets          | 31742000 | 2020
21   | Damian Lillard    | PG       | Portland Trail Blazers | 29802321 | 2020
52   | Malcolm Brogdon   | PG       | Indiana Pacers         | 20000000 | 2020
... (72 rows omitted)

In [73]:
point_guards = point_guards.drop('rank', 'position', 'season')

In [74]:
point_guards.show(10)

In [76]:
point_guards.sort('salary', descending=True).show(10)

In [78]:
# The line below will cause a value error
nba.where('position', 'PG').drop('position')

rank | name             | team                   | salary   | season
8    | Gary Payton      | Seattle SuperSonics    | 11020000 | 2000
11   | Damon Stoudamire | Portland Trail Blazers | 10125000 | 2000
20   | Stephon Marbury  | New Jersey Nets        | 9000000  | 2000
24   | Nick Van Exel    | Denver Nuggets         | 8354000  | 2000
26   | Terrell Brandon  | Minnesota Timberwolves | 7400000  | 2000
34   | Jason Kidd       | Phoenix Suns           | 6858000  | 2000
35   | Kenny Anderson   | Boston Celtics         | 6680000  | 2000
39   | Steve Nash       | Dallas Mavericks       | 5500000  | 2000
55   | Charlie Ward     | New York Knicks        | 4540000  | 2000
61   | Darrel Armstrong | Orlando Magic          | 4125000  | 2000
... (1465 rows omitted)